# ==========================================================
# Cinfer 内置模型定义文件 (Built-in Models Definition)
# ==========================================================
#
# 此文件定义了所有系统自带的、在数据库初始化时需要植入的内置模型。

models:
  - id: "Camthink-OCRv1"
    name: "Camthink-OCRv1"
    remark: "A standard, system-provided object detection model."
    engine_type: "ocr"
    file_path: "built-in/paddle"
    params_path: "built-in/paddle/params.yaml"
    status: "draft"
    is_built_in: true

  # - id: "builtin-resnet-classification"
  #   name: "ResNet50 Classification (Built-in
