# 服务配置
server:
  host: "0.0.0.0" 
  port: 8000 
  workers: 1
  log_level: "INFO" 

database:
  type: "sqlite"
  path: "data/db/cinfer.db" # Ensure this path is writable

# For JWT secret (used by cinfer/utils/security.py)
auth:
  jwt_secret_key: "cinfer-jwt-secret-key" #
  jwt_algorithm: "HS256"
  # For X-Auth-Token (internal admin sessions)
  admin_access_token_expire_minutes: 1440   # 24 hours for AT, as requested
  admin_refresh_token_expire_minutes: 1440  # 24 hours for RT, as requested (typically longer)

  # For X-Access-Token (external API access)
  jwt_access_token_expire_days: 36500 # 100 years
  rate_limit:
    default_requests_per_minute: 60
    default_period_seconds: 60

# For EngineService and QueueManager defaults
engines:
  onnx: # Example for onnx, add others if used as default
    threads: 0 # 0 for auto
    # max_workers: 2 # (optional, can be derived from request.workers_per_model)
    # queue_size: 50 # (optional, can be derived from request.queue_size)

request:
  queue_size: 100 # Default max queue size per model
  workers_per_model: 2 # Default workers per model
  timeout_ms: 10000 # Default sync request timeout

models:
  storage_path: "data/models"
  default_yaml_path: "config/template.yaml"

logging:
  format: "%(levelname)s - %(asctime)s - %(module)s:%(lineno)d: %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"
  file:
    path: data/logs/log 
    max_bytes: 5242880
    backup_count: 5

system:
  name: "CamThink AI Inference Platform"
  version: "1.0.0"